# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'RetryableNetworkQueries' do
	pod 'AFNetworking', '~> 2.5'
end

target 'RetryableNetworkQueriesTests' do
    pod 'AFNetworking', '~> 2.5'
end

